baseURL = 'https://github.com/vincent-lau/blog/'
languageCode = 'en-us'
title = 'Denotational Logs'
theme = "PaperMod"

custom_css=["css/custom.css"]
custom_js = ["ja/custom.js"]

sectionPagesMenu = "main"
