baseURL = 'https://vincent-lau.github.com/blog/'
languageCode = 'en-us'
title = 'Denotational Logs'
theme = "PaperMod"

custom_css=["css/custom.css"]
custom_js = ["ja/custom.js"]

sectionPagesMenu = "main"
